version: 0.0 #version은 필수 값이며 0.0이 고정입니다.
os: linux #ec2에 배포하는 경우 필수 값이며, amazon linux를 사용하므로 linux를 입력합니다.

files:
  - source: /
    destination: /home/jenkins/deploy

hooks:
  BeforeInstall:
    - location: remove_before.sh #BeforeInstall 생명주기에, 이전에 생성된 파일들을 제거하는 remove_before.sh를 실행합니다.
  AfterInstall:
    - location: kill_process.sh #ApplicationStop 생명주기에, kill_process.sh를 실행합니다

